x = int(input())
y = int(input())
print(x*y)
print("Length of the rectangle is",x,"and breadth is",y,".")
print("Hence the area of the rectangle is (length*breadth).")
print("So the answer is",x,"*",y,"=",x*y)
